### ISSUE TITLE
NO USB Wifi Device Plugged in

### ISSUE THREAD

**Issue by tlefko** [chris1111/Wireless-USB-Big-Sur-Adapter#10]
Followed all instructions for gatekeeper and SIP to a tee. The device is detected in system information but the menu bar shows no USB wifi detected. On beta 20A4300b. Know it's not the USB wifi as works fine under windows and worked under Catalina.

**Note at first the prompt for extension showed up, allowed it. After uninstall and reinstall it no longer appears. -- in both cases no USB found. My csrutil status is disabled (apple internal)

Any suggestions? The USB is supported and is realtek (exact model not known but worked under catalina) something AC1200M
Tried both USB 3 and USB 2. Note* No options  were added to network preferences. Tried reset them no luck

**Comment by chris1111** [comment]
Uninstall 
reboot to recovery Enable SIP reboot then reboot to recovery again and Disable SIP
Run the program Allow Realtek only, uncheck Other Allow

**Comment by tlefko** [comment]
will try and update results @chris1111

**Comment by chris1111** [comment]
Its work here

**Comment by chris1111** [comment]
macOS Big Sur 11 Beta 3 test on MacBook Pro late 2013
See Video
[![Modular Image Creation](https://i87.servimg.com/u/f87/17/99/48/98/68747410.png)](https://youtu.be/8q_5UGfK5Mk)

**Comment by tlefko** [comment]
> macOS Big Sur 11 Beta 3 test on MacBook Pro late 2013
> See Video
> [![Modular Image Creation](https://camo.githubusercontent.com/0636d1609f67e41ee3e7635b7aff524948e8fc7b/68747470733a2f2f6938372e73657276696d672e636f6d2f752f6638372f31372f39392f34382f39382f36383734373431302e706e67)](https://youtu.be/8q_5UGfK5Mk)

yeah that happened to me but still no USB found. I will try on laptop now

**Comment by tlefko** [comment]
@chris1111 marked as resolved -- make sure you instruct users to have sip completely disabled not just thru apple internal --- CSR (Cambridge silicon) needs to be disabled in extensions

**Comment by chris1111** [comment]
> @chris1111 marked as resolved -- make sure you instruct users to have sip completely disabled not just thru apple internal --- CSR (Cambridge silicon) needs to be disabled in extensions
this is written Working SIP disable on Beta 3

**Comment by chris1111** [comment]
> @chris1111 marked as resolved -- make sure you instruct users to have sip completely disabled not just thru apple internal --- CSR (Cambridge silicon) needs to be disabled in extensions


this is written Working SIP disable on Beta 3

**Comment by tlefko** [comment]
> > @chris1111 marked as resolved -- make sure you instruct users to have sip completely disabled not just thru apple internal --- CSR (Cambridge silicon) needs to be disabled in extensions
> 
> this is written Working SIP disable on Beta 3

I ran on Beta 2 -- I had sip disabled through recovery which returns Sip disabled (apple Internal). this won't work. Enabling CSR breaks Wifi as well

**Comment by chris1111** [comment]
of course that yes if you have allocated extensions before it can cause problems you must understand that it is a BETA and only the third

**Comment by tlefko** [comment]
> of course that yes if you have allocated extensions before it can cause problems you must understand that it is a BETA and only the third

yeah you're totally right. I didn't realize because the installer tries to have you allow caimbridge but that's my model of USB, maybe include in the instructions to do Realtek only. great work

**Comment by jeremybeny** [comment]
> Followed all instructions for gatekeeper and SIP to a tee. The device is detected in system information but the menu bar shows no USB wifi detected. On beta 20A4300b. Know it's not the USB wifi as works fine under windows and worked under Catalina.
> 
> **Note at first the prompt for extension showed up, allowed it. After uninstall and reinstall it no longer appears. -- in both cases no USB found. My csrutil status is disabled (apple internal)
> 
> Any suggestions? The USB is supported and is realtek (exact model not known but worked under catalina) something AC1200M
> Tried both USB 3 and USB 2. Note* No options were added to network preferences. Tried reset them no luck

can you help me solving the same problem? I have done everything posted here but still not detecting my usb Edimax EW-7822ULC  thank you
