### ISSUE TITLE
Just got public beta for Big Sur, the driver for netgear 7000 adapter is not working

### ISSUE THREAD

**Issue by jclocker** [chris1111/Wireless-USB-Big-Sur-Adapter#11]
The new driver for Big Sur is not working with the netgear 7000 adapter getting no usb-wifi plug in and no blue light on the A7000 adapter connected to USB port and tested with USB powered hub. Not seeing the adapter on MacBook Pro 16 2019 model.
![Screen Shot 2020-08-06 at 5 41 40 PM](https://user-images.githubusercontent.com/69326592/89585601-1ca4f000-d80c-11ea-92f6-5e6b2aab9dc3.png)

**Comment by chris1111** [comment]
Do you have SIP security turned off? Did you also follow all the steps?

**Comment by jclocker** [comment]
Chris will have to check. Will let you know.

**Comment by jclocker** [comment]
Chris in the video you show running gatekeeper.command from the desktop folder. Is this a script? Still having problems with the Big Sur showing No USB-WIFI  Plug in. The Netgear A7000 works when I am in bootcamp and window 10 but still not in Big Sur. 

Thanks for any help Jim a fan of your software
