### ISSUE TITLE
Installation failed on Big Sur 11.4

### ISSUE THREAD

**Issue by arpsyapathy** [chris1111/Wireless-USB-Big-Sur-Adapter#111]
Hi!

I download .pkg for Big Sur.
Try install on my hackintosh Big Sur 11.4 on vmware. 
But i get "Installation failed" =(

How can i fix this?

Thank you advanced

**Comment by chris1111** [comment]
SIP not fully disable

csrutil disable 
csrutil authenticated-root disable
