### ISSUE TITLE
No USB-WiFi Plugin 

### ISSUE THREAD

**Issue by danielaconsti** [chris1111/Wireless-USB-Big-Sur-Adapter#119]
Hi, after successfully installing V7 as described in the instructions I'm still unable to use the adapter (RTL8188EU). 

<img width="355" alt="Screen Shot 2021-06-29 at 21 44 35" src="https://user-images.githubusercontent.com/3704877/123885195-50f13580-d923-11eb-94fd-dd749fea4184.png">

I also did a fresh install of macOS Big Sur and reinstalled everything again and it doesn't work

<img width="264" alt="Screen Shot 2021-06-29 at 21 46 04" src="https://user-images.githubusercontent.com/3704877/123885264-75e5a880-d923-11eb-8a92-66bc1b8e7f77.png">

Do you know what could be causing this issue?

**Comment by chris1111** [comment]
RTL8188EU is not support anymore in new macOS  its old and is remove by realtek

**Comment by danielaconsti** [comment]
Sorry, I have the RTL8812AU

It's an Alfa Awus036ach Wifi Dual Band clone

**Comment by chris1111** [comment]
> Sorry, I have the RTL8812AU
> 
> It's an Alfa Awus036ach Wifi Dual Band clone

Is support by the program , make sur SIP is fully disable thens try other USB port

**Comment by danielaconsti** [comment]
SIP is fully disabled and I've tried both USB ports :(

**Comment by chris1111** [comment]
> SIP is fully disabled and I've tried both USB ports :(


Uninstall the program

then try this 

[Wireless USB Big Sur Adapter-V-7.zip](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/6744517/Wireless.USB.Big.Sur.Adapter-V-7.zip)

**Comment by chris1111** [comment]
Uninstall the program but Reboot macOS 

then try this 

[Wireless USB Big Sur Adapter-V-7.zip](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/6744517/Wireless.USB.Big.Sur.Adapter-V-7.zip)

**Comment by chris1111** [comment]
Uninstall like this
![Screen Shot 2021-06-30 at 7 56 29 PM](https://user-images.githubusercontent.com/6248794/124045341-6c207b80-d9dd-11eb-9817-e933bd02fcb4.png)

Then Reboot
after reboot use the program attaching UP

**Comment by danielaconsti** [comment]
IT WORKS NOWWWW THANKS!

**Comment by chris1111** [comment]
> IT WORKS NOWWWW THANKS!

Glad to hear that 😏

**Comment by Luisalbert21** [comment]
![IMG_20210719_183142](https://user-images.githubusercontent.com/87678629/126244126-d1d5ff67-5d37-408a-9f64-0cbdcdf64466.jpg)
Ya instalé correctamente la V7 pero mi antena mi macOs Big Sur sige sin reconocer la antena

**Comment by Luisalbert21** [comment]
Le explico instalé el adaptador de usb para macOs Big Sur V7 en mi mac pero no detecta la antena si me puede ayudar porfavor
