### ISSUE TITLE
Installation fails on macOS Big Sur 11.5 

### ISSUE THREAD

**Issue by norbertschuler** [chris1111/Wireless-USB-Big-Sur-Adapter#126]
On macOS Big Sur 11.5 the installation fails as following (German version):

<img width="674" alt="Bildschirmfoto 2021-07-22 um 11 20 34" src="https://user-images.githubusercontent.com/1532418/126616890-2a25c8db-f91c-4d5b-916d-774f9685d8d0.png">

Are there any logs which I can check?

This is my csrutil status working well before:
```
$ csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: enabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

```

**Comment by norbertschuler** [comment]
My prior installed driver still worked after a restart of my MacBook.

**Comment by chris1111** [comment]
This is strange I dont have issue on 11.5  update last night
![Screen Shot 1](https://user-images.githubusercontent.com/6248794/126632357-9671b76a-5ae8-4a89-85d1-f783e83dbb37.png)

**The Log can be save a the top bar - Window**
![Screen Shot 2](https://user-images.githubusercontent.com/6248794/126632360-f525c124-beb5-4cc2-bcb9-e1a85f17100c.png)

**Save**
![Screen Shot 3](https://user-images.githubusercontent.com/6248794/126632362-53602858-5a7a-4815-b3f0-2090876cec17.png)

**Show all Log**
![Screen Shot 4](https://user-images.githubusercontent.com/6248794/126632364-78208f9e-1206-4af3-a485-9f8bb4fd214d.png)

**Comment by norbertschuler** [comment]
I can share my install.log (this is from just running the installer again despite already having the software installed - I've not tried removing it before):

[install.log](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/6862000/install.log)

**Comment by chris1111** [comment]
Missing Info from your LOG log is not complete
![image](https://user-images.githubusercontent.com/6248794/126660963-0c3017f6-c2af-46c4-9ab2-582776f42075.png)

**Comment by norbertschuler** [comment]
Sorry. Probably my `Filesystem Protections: enabled` made is fail as I did not disable everything with `csrutil` as you wrote in your description (s. above) - sorry for asking then:

[install.log](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/6863491/install.log)

**Comment by chris1111** [comment]
Something wrong about your macOS  or the SIP ?
If you use a old macbook patching dosdude1 or OCLP 
try to disable SIP and File system 
csrutil disable
csrutil authenticated-root disable
