### ISSUE TITLE
Possible to create a notorized pkg ?

### ISSUE THREAD

**Issue by APwhitehat** [chris1111/Wireless-USB-Big-Sur-Adapter#135]
Possible to notorize the kext and pkg by Apple ? https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution 
Then we may be able to run this driver without the need to keep SIP disabled.

This solution worked for hoRNDIS https://github.com/jwise/HoRNDIS/issues/132#issuecomment-745607263

**Comment by chris1111** [comment]
Thanks I will make a test on my macBook Pro if that work I Update the programme

**Comment by chris1111** [comment]
sadly from PKG its work only with the OC version
