### ISSUE TITLE
Wireless always disconnect when I start a Virtual Box VM.

### ISSUE THREAD

**Issue by worapojc** [chris1111/Wireless-USB-Big-Sur-Adapter#139]
Hi,

I'm using ASUS-N13 USB. 

It's working fine on MacOS but it always disconnect when I start a Virtual Box VM.
I want to bridge the USB wireless network (en8) with the virtual box and is not working.
I also tried to bridge the main wireless (en0) and the USB wireless will be disconnected too.

It will re-connect when I stop the Virtual Box VM.

Cheers

**Comment by sooothooot201** [comment]
Kodi

**Comment by chris1111** [comment]
This is relate to a virtual Box issue I think
