### ISSUE TITLE
No USB-Wifi plugin

### ISSUE THREAD

**Issue by styl3zs** [chris1111/Wireless-USB-Big-Sur-Adapter#140]
Hi, I've tried multiple times to install the driver for my Asus USB-AC51, but it gives me the error that the application can't find the USB adapter. 

Am I doing something wrong?

**Comment by chris1111** [comment]
You are not read the page correctly Mediatek Drivers is not support here
You have an adapter using the RT2870USBWirelessDriver.kext from Mediatek so its not the same from here.
Closed
