### ISSUE TITLE
Update for Big Sur Beta 6

### ISSUE THREAD

**Issue by Mxkkxa** [chris1111/Wireless-USB-Big-Sur-Adapter#15]
It is not working anymore on Beta 6 version of Big Sur, an update is needed. Thank you.

**Comment by chris1111** [comment]
Really ![296233927](https://user-images.githubusercontent.com/6248794/92594018-25a43980-f270-11ea-8299-2aa147a210ce.gif)

![Screen Shot 1](https://user-images.githubusercontent.com/6248794/92594033-2f2da180-f270-11ea-88de-cd1951f1afec.png)
![Screen Shot 2](https://user-images.githubusercontent.com/6248794/92594037-318ffb80-f270-11ea-8aac-fb1e2551aee1.png)
![Screen Shot 3](https://user-images.githubusercontent.com/6248794/92594040-318ffb80-f270-11ea-8475-4ef8f55583e0.png)
![Screen Shot 4](https://user-images.githubusercontent.com/6248794/92594041-32289200-f270-11ea-848b-53bd67abedce.png)
