### ISSUE TITLE
M1 chip

### ISSUE THREAD

**Issue by Gwindor** [chris1111/Wireless-USB-Big-Sur-Adapter#151]
There is a note that is doesn't work on M1. Do you think it is possible to make it work on it?

**Comment by chris1111** [comment]
I dont think so

**Comment by evg1n** [comment]
Hello,

I know this is closed but I wanted to share my experience.
My device is MBP 13" w/ M1. Below is my installer log. The AOT compiler fails when processing driver binaries. If you don't have an Apple Silicon, with your guidance, we can progress on my machine.

Appreciate your work. Thanks in advance.

`@(#)PROGRAM:Install  PROJECT:Install-1000
@(#)PROGRAM:Installer  PROJECT:Installer-1102
Hardware: MacBookPro17,1 @ 2.40 GHz (x 8), 16384 MB RAM
Running OS Build: macOS 12.0.1 (21A559)
Env: xfffff748aef51ad0=18446734490277845712 1
Env: xfffff74fb61edad0=18446734520462793424 1
Env: PWD=/private/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless USB Big Sur Adapter.app/Contents/Resources
Env: xfffff724b2c40ad0=18446734335722916560 1
Env: xfffff7369033ead0=18446734412452457168 1
Env: xfffff726655acad0=18446734343014107856 1
Env: ICNS=.
Env: xfffff72a5e51cad0=18446734360075946704 1
Env: xfffff74c5b9cfad0=18446734506059430608 1
Env: xfffff74ab6077ad0=18446734498986425040 1
Env: xfffff73ca0d70ad0=18446734438501386960 1
Env: xfffff73b81f30ad0=18446734433688160976 1
Env: xfffff74eaee07ad0=18446734516046297808 1
Env: xfffff7381f8c4ad0=18446734419152358096 1
Env: xfffff72d9bb15ad0=18446734373990521552 1
Env: xfffff7271399dad0=18446734345937476304 1
Env: xfffff72a37724ad0=18446734359423765200 1
Env: xfffff73c13fcfad0=18446734436138285776 1
Env: xfffff729f1904ad0=18446734358251326160 1
Env: xfffff737c4336ad0=18446734417619806928 1
Env: xfffff73dd1552ad0=18446734443609926352 1
Env: xfffff74a68ce7ad0=18446734497690843856 1
Env: xfffff724a239cad0=18446734335445420752 1
Env: xfffff73d870e2ad0=18446734442363759312 1
Env: USER=evg1n
Env: xfffff72a2bbdfad0=18446734359227398864 1
Env: xfffff73a4ac15ad0=18446734428467190480 1
Env: xfffff729fb547ad0=18446734358415178448 1
Env: xfffff73f260a6ad0=18446734449326058192 1
Env: xfffff74cd26f1ad0=18446734508052912848 1
Env: xfffff74f899e3ad0=18446734519716166352 1
Env: xfffff73c69d05ad0=18446734437578201808 1
Env: xfffff748ad837ad0=18446734490253621968 1
Env: xfffff725dd5faad0=18446734340732725968 1
Env: xfffff74ff91a6ad0=18446734521586576080 1
Env: COMMAND_MODE=unix2003
Env: xfffff73621fe8ad0=18446734410603465424 1
Env: xfffff74e11685ad0=18446734513404402384 1
Env: xfffff74efaedbad0=18446734517322234576 1
Env: xfffff749a9fc6ad0=18446734494489406160 1
Env: xfffff73de6f32ad0=18446734443972602576 1
Env: xfffff73c57033ad0=18446734437262768848 1
Env: xfffff74e68425ad0=18446734514861529808 1
Env: xfffff74e7cfa3ad0=18446734515209124560 1
Env: xfffff74c60f96ad0=18446734506149374672 1
Env: xfffff73de1990ad0=18446734443882810064 1
Env: __CFBundleIdentifier=com.apple.installer
Env: xfffff74827d5ead0=18446734488010877648 1
Env: LOGNAME=evg1n
Env: xfffff74e6a6e1ad0=18446734514897951440 1
Env: xfffff73b70510ad0=18446734433392331472 1
Env: xfffff72dfbb94ad0=18446734375601654480 1
Env: xfffff746c21eead0=18446734482009418448 1
Env: xfffff734f6d7aad0=18446734405584530128 1
Env: PATH=/usr/bin:/bin:/usr/sbin:/sbin
Env: xfffff73b127f7ad0=18446734431818316496 1
Env: xfffff74bbf6d9ad0=18446734503439080144 1
Env: xfffff7373d57fad0=18446734415357278928 1
Env: xfffff72865022ad0=18446734351598234320 1
Env: xfffff74a4c12aad0=18446734497208773328 1
Env: xfffff74d1e5c4ad0=18446734509326748368 1
Env: xfffff746c293fad0=18446734482017090256 1
Env: xfffff74c82a07ad0=18446734506713971408 1
Env: xfffff74a30d1ead0=18446734496751545040 1
Env: xfffff74f3ca8dad0=18446734518425017040 1
Env: xfffff746b942fad0=18446734481860786896 1
Env: xfffff736d29f9ad0=18446734413566810832 1
Env: xfffff73d47ec7ad0=18446734441304586960 1
Env: xfffff749f129cad0=18446734495683562192 1
Env: xfffff74c61870ad0=18446734506158656208 1
Env: xfffff74bda058ad0=18446734503885245136 1
Env: xfffff72a8e1c4ad0=18446734360877746896 1
Env: xfffff72d71c36ad0=18446734373287062224 1
Env: xfffff727f528fad0=18446734349721729744 1
Env: xfffff72d419dfad0=18446734372479302352 1
Env: SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS=/Users/evg1n/Library/WebKit/Databases
Env: xfffff74ab3bc8ad0=18446734498947959504 1
Env: xfffff729610f2ad0=18446734355826944720 1
Env: xfffff74b4b920ad0=18446734501495311056 1
Env: xfffff73c2cb2aad0=18446734436552846032 1
Env: SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.yRttQoAd9A/Listeners
Env: xfffff73ba2a9ead0=18446734434237016784 1
Env: xfffff748c8e81ad0=18446734490713201360 1
Env: xfffff72836445ad0=18446734350814042832 1
Env: xfffff73abf352ad0=18446734430420937424 1
Env: xfffff74ed9ca4ad0=18446734516766264016 1
Env: xfffff72d2c0f1ad0=18446734372117617360 1
Env: SHLVL=2
Env: xfffff74ce3b11ad0=18446734508342450896 1
Env: xfffff74c57377ad0=18446734505985669840 1
Env: xfffff728439fdad0=18446734351038143184 1
Env: xfffff74f05fe6ad0=18446734517507877584 1
Env: xfffff73bce3cead0=18446734434968070864 1
Env: xfffff74e71135ad0=18446734515009444560 1
Env: xfffff7490886ead0=18446734491780573904 1
Env: xfffff7262a5eead0=18446734342024522448 1
Env: xfffff73c0963bad0=18446734435960470224 1
Env: xfffff74e6dd1fad0=18446734514954828496 1
Env: xfffff7482c430ad0=18446734488085138128 1
Env: xfffff737363d3ad0=18446734415238085328 1
Env: xfffff746f51acad0=18446734482864786128 1
Env: xfffff7284d75fad0=18446734351203171024 1
Env: HOME=/Users/evg1n
Env: xfffff74b0d701ad0=18446734500452899536 1
Env: xfffff748d81c7ad0=18446734490968292048 1
Env: xfffff7286d7b0ad0=18446734351740373712 1
Env: xfffff72921f84ad0=18446734354768480976 1
Env: _=/usr/bin/Open
Env: SHELL=/bin/zsh
Env: xfffff7385d6d9ad0=18446734420190534352 1
Env: xfffff72785eaead0=18446734347855391440 1
Env: xfffff7381f1b7ad0=18446734419144964816 1
Env: xfffff73a029d9ad0=18446734427256888016 1
Env: xfffff7267fd2dad0=18446734343458183888 1
Env: xfffff74c07ffaad0=18446734504656612048 1
Env: xfffff72aeb0aead0=18446734362436889296 1
Env: xfffff73b23c75ad0=18446734432108239568 1
Env: xfffff74cd3053ad0=18446734508062751440 1
Env: xfffff746c47fbad0=18446734482049317584 1
Env: xfffff736f0c5fad0=18446734414072642256 1
Env: xfffff748a8eccad0=18446734490176637648 1
Env: TMPDIR=/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/
Env: __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
Env: xfffff74dcb3d5ad0=18446734512227179216 1
Env: xfffff73af4a04ad0=18446734431317150416 1
Env: xfffff74d7d545ad0=18446734510920063696 1
Env: XPC_SERVICE_NAME=application.com.apple.installer.1152921500312163505.1152921500312163510
Env: XPC_FLAGS=0x0
Wireless USB Big Sur Adapter-V-11  Installation Log
Opened from: /var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless USB Big Sur Adapter.app/Contents/Resources/.Files/Wireless USB Big Sur Adapter.pkg
Product archive /var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless USB Big Sur Adapter.app/Contents/Resources/.Files/Wireless USB Big Sur Adapter.pkg trustLevel=100
External component packages (5) trustLevel=100 (trust evaluation failed: Error Domain=PKInstallErrorDomain Code=101 "The package “Wireless USB Big Sur Adapter.pkg” is not signed." UserInfo={NSURL=#uninstall.pkg -- file:///var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless%20USB%20Big%20Sur%20Adapter.app/Contents/Resources/.Files/Wireless%20USB%20Big%20Sur%20Adapter.pkg#Distribution, PKInstallPackageIdentifier=com.109Driver.wirelessUsbBigSurAdapter.uninstall.pkg, NSLocalizedDescription=The package “Wireless USB Big Sur Adapter.pkg” is not signed.})
Could not load resource license: (null)
================================================================================
User picked Custom Install
Choices selected for installation:
	Install: "Wireless USB Big Sur Adapter-V-11"
	Install: "Wireless USB Big Sur Adapter"
		Wireless USB Big Sur Adapter.pkg#statusbarapp.pkg : com.109Driver.wirelessUsbBigSurAdapter.statusbarapp.pkg : 1.0
		Wireless USB Big Sur Adapter.pkg#agents.pkg : com.109Driver.wirelessUsbBigSurAdapter.Agents.pkg : 1.0
		Wireless USB Big Sur Adapter.pkg#daemon.pkg : com.109Driver.wirelessUsbBigSurAdapter.Daemon.pkg : 1.0
		Wireless USB Big Sur Adapter.pkg#drivers.pkg : com.109Driver.wirelessUsbBigSurAdapter.Drivers.pkg : 1.0
It took 0.00 seconds to summarize the package selections.
Administrator authorization granted.
User picked Standard Install
-[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
-[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless%20USB%20Big%20Sur%20Adapter.app/Contents/Resources/.Files/Wireless%20USB%20Big%20Sur%20Adapter.pkg#statusbarapp.pkg
-[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless%20USB%20Big%20Sur%20Adapter.app/Contents/Resources/.Files/Wireless%20USB%20Big%20Sur%20Adapter.pkg#agents.pkg
-[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless%20USB%20Big%20Sur%20Adapter.app/Contents/Resources/.Files/Wireless%20USB%20Big%20Sur%20Adapter.pkg#daemon.pkg
-[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T/AppTranslocation/9E29B4E2-F748-41B2-AC6B-4F1CE8308B5D/d/Wireless%20USB%20Big%20Sur%20Adapter.app/Contents/Resources/.Files/Wireless%20USB%20Big%20Sur%20Adapter.pkg#drivers.pkg
Set authorization level to root for session
Will use PK session
Using authorization level of root for IFPKInstallElement
Install request is requesting Rosetta translation.
Starting installation:
Configuring volume "Macintosh HD"
Preparing disk for local booted install.
Free space on "Macintosh HD": 151,31 GB (151306252288 bytes).
Create temporary directory "/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T//Install.2236HVY57b"
IFPKInstallElement (4 packages)
Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
PackageKit: Enqueuing install with framework-specified quality of service (utility)
Running install actions
Removing temporary directory "/var/folders/ts/hfqwnbt96jx0j0vlskbnt6mm0000gn/T//Install.2236HVY57b"
Finalize disk "Macintosh HD"
Notifying system of updated components

**** Summary Information ****
  Operation      Elapsed time
-----------------------------
       disk      0.02 seconds
     script      0.00 seconds
       zero      0.01 seconds
    install      10.05 seconds
    -total-      10.07 seconds
IFDInstallController 16FE080 state = 5
Displaying 'Install Succeeded' UI.`

**Comment by ezekiel747** [comment]
what would it take to support the M1 chip?
unfortunately for some of us, neither the official drivers are not supported (TP-Link in my case) and don't have any alternative.

**Comment by chris1111** [comment]
You can try to use the [Notorized Guide](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/159) and 
csrutil enable --without kext
Not csrutil disable

**Comment by shmizan** [comment]
@chris1111 thanks for all of your hard work.
all new macs are now Apple chips, and since TP-LINK and the rest of these companies can't seem to work out a solution, only you can help!
@evg1n has offered to help with your instructions on his machine.. maybe we can try that direction?
it will be very helpful since NO other solution exists.

**Comment by jlk** [comment]
@chris1111 Just a data point - I tried 
```
csrutil disable
csrutil enable --witout kext
``` 
from recovery mode, but I still see "No USB-WiFi Plug in" from the menubar icon. This is an 16" M1 macbook pro.

I plugged the adapter into a raspi just to verify, and it's showing up as a realtek nic:
```
  idVendor           0x0bda Realtek Semiconductor Corp.
  idProduct          0xc811
  bcdDevice            2.00
  iManufacturer           1 Realtek
  iProduct                2 802.11ac NIC
  iSerial                 3 123456
```

**Comment by Tobias-Conrad** [comment]
@chris1111 Chris what needs you to do it? And us to get Wifi working via your solution?

**Comment by Tobias-Conrad** [comment]
@chris1111 Chris what needs you to do it? And us to get Wifi working via your solution?
