### ISSUE TITLE
No USB-WiFi Plug in

### ISSUE THREAD

**Issue by sarrathy** [chris1111/Wireless-USB-Big-Sur-Adapter#156]
I tried using Archer T2U Nano . it still says No USB-WiFi Plug in . Please help

**Comment by chris1111** [comment]
Reboot then unplug adapter and replug

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/83#discussioncomment-1722632

**Comment by sarrathy** [comment]
> Reboot then unplug adapter and replug try diferant USB Port

Still no improvement , it still shows the same error .

**Comment by sarrathy** [comment]
<img width="341" alt="Screenshot 2021-12-01 at 11 06 58 AM" src="https://user-images.githubusercontent.com/15632081/144178042-f4dcaed7-12c5-4d70-9f08-58e7e9ee7f23.png">

**Comment by sarrathy** [comment]
<img width="334" alt="Screenshot 2021-12-01 at 11 07 44 AM" src="https://user-images.githubusercontent.com/15632081/144178097-7e30146e-9812-4a99-8e21-dae4a10b9c9e.png">

**Comment by sarrathy** [comment]
<img width="309" alt="Screenshot 2021-12-01 at 11 09 54 AM" src="https://user-images.githubusercontent.com/15632081/144178155-67e94e80-3483-4d45-8074-bac2e3b9be53.png">
