### ISSUE TITLE
Doesn't recognize the drive after its disconnected

### ISSUE THREAD

**Issue by ninjacarlo** [chris1111/Wireless-USB-Big-Sur-Adapter#163]
Hi, 

My wireless adapter works at first, directly after installing your software and then rebooting.
But if I unplug the adapter, when I plug it back in, it doesn't get recognized anymore, and the app behaves as if it isn't plugged in.
I've got the Cudy W600 adapter (for example the Cudy W700 is already in the supported list).

Then if I reboot the mac again, it recognizes it again. 
So basically I have to reboot my machine to make it work after being disconnected.

**Comment by chris1111** [comment]
I dont have this problem with 6 USB adapter; already test this 
Probably relate to your adapter or USB port?
Try to replug on USB 2 port
