### ISSUE TITLE
The WiFi is not stable

### ISSUE THREAD

**Issue by amri07** [chris1111/Wireless-USB-Big-Sur-Adapter#164]
The icon bar on latest BigSur(last update of BigSur) keeps running USB-WiFi Scan Networks after time to time. It won't work like normal adapter. I'm using it as my main wifi adapter to connect to my private network at home and after several minutes of running the network will be disconnected and it's scanning all over the network again. Did i misconfigured something ? Is it possible to fix this ? Thank you

**Comment by chris1111** [comment]
Not possible to make it better because no source of the drivers exist
