### ISSUE TITLE
Can not be used as part of Internet Shared

### ISSUE THREAD

**Issue by Johnne25** [chris1111/Wireless-USB-Big-Sur-Adapter#168]
You can not use this as a connection for the computer to use Mac's ethernet internet connection.

You can configure it, but it doesn't broadcast its SID so users can not connect to the Mac using WIFI.

**Comment by chris1111** [comment]
Its WIFI not ethernet

[Read this](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/133)

**Comment by Johnne25** [comment]
I understand that.  My Mac has an ethernet connection which is used for the Internet.
I want to use USB WIFI (and this driver) to setup Internet Sharing on the Mac.  Users connect to the Mac using WIFI to access its Ethernet internet connection.

**Comment by chris1111** [comment]
Not possible to setup Internet Sharing with this Drivers
