### ISSUE TITLE
Archer T2U Nano doesn't work on this version

### ISSUE THREAD

**Issue by matthvalenca11** [chris1111/Wireless-USB-Big-Sur-Adapter#173]
Hi, Chris

Can you send me the oldest versions of the Wireless-USB-Big-Sur Adapter, Archer T2U Nano, for my Wi-Fi adapter the older versions used to work on my hackintosh.

Here is my e-mail: mathvalenca@gmail.com
Best regards,
Matheus.

**Comment by chris1111** [comment]
No Older its the only one
