### ISSUE TITLE
Source code & installer / driver security

### ISSUE THREAD

**Issue by mtrezza** [chris1111/Wireless-USB-Big-Sur-Adapter#176]
Is the source code of the modified driver / installer published anywhere? Or is there any other way to verify that the package is save?

**Comment by chris1111** [comment]
Package is not Sign, but its safe you can use the drivers and utility SIP enable
If you what to check it use Suspicious Package
![Screen Shot 2022-01-27 at 4 03 52 PM](https://user-images.githubusercontent.com/6248794/151443463-cfe278e9-4ec3-4e79-aa16-9d6a36854452.png)

**Comment by chris1111** [comment]
If you whant to Sign in, Use CLI **productsign**
`productsign --sign "Developer ID Installer: Your Developer Name
(1A2B3C4D5E)" ~/Desktop/"USB Big Sur Adapter.pkg" ~/Desktop/signed-"USB Big Sur Adapter.pkg"`

**Comment by mtrezza** [comment]
I think my question goes beyond signing, which is just a formal step. It would be interesting to know which changes have been made to the driver (if any) and which scripts are executed by the installer.

**Comment by mtrezza** [comment]
I just found https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/159.

Are the drivers original Realtek drivers?

**Comment by chris1111** [comment]
original
