### ISSUE TITLE
No USB-WIFI Plug In after reboot

### ISSUE THREAD

**Issue by fortoszone** [chris1111/Wireless-USB-Big-Sur-Adapter#183]
I have TP-TL725WN on Monterey 12.1. It works but after few reboots it just not detected anymore. I have to reinstall the driver to make it work again. Already tried to change port but still no clue. Any idea why? Here's my [spec and efi](https://github.com/fortoszone/hekintush-oc)

**Comment by chris1111** [comment]
Sorry but is the drivers works for you and and couple reboot later it does not work , you have to find the reason because its not my job
