### ISSUE TITLE
Wrong Wifi Password Monterey 12.2.1

### ISSUE THREAD

**Issue by compyy** [chris1111/Wireless-USB-Big-Sur-Adapter#187]
Hello, Thanks for such great work, i have a question sometimes when i wake my Macbook pro intel from sleep, Wifi doesnt connect and it keeps giving me error wrong password, but if i reload the PC it works fine.

Not sure how to start troubleshooting it ? any thing you can help ? which logs should i collect at the time of issue ? with which command.

**Comment by compyy** [comment]
Hi, if i disable the adapter and reenable after 5 to 10 minutes, it works fine, most probably restart of service works, can you tell me which service is it running or process which i can kill and restart from activity monitor ?

**Comment by xuzhirui123** [comment]
me too

**Comment by xuzhirui123** [comment]
who can help me?thanks

**Comment by chris1111** [comment]
Thats not append on my 6 adapter.
This is as no relation with Wireless-USB-OC-Big-Sur-Adapter, its relate to your side
Issue closed
