### ISSUE TITLE
Archer T3U Plus supported on macOS Big Sur?

### ISSUE THREAD

**Issue by arshak-kahnputers** [chris1111/Wireless-USB-Big-Sur-Adapter#19]
I was about to purchase T3U Plus which is supported on Catalina, but on Big Sur it is not listed under known working and testing adapter. I'll be using it on hackintosh build, so I was wondering would it be supported? Please let me know.

**Comment by chris1111** [comment]
Yes

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/commit/bba603c44518d71d9684eabd8f768cad6ae902c1
