### ISSUE TITLE
8812au/8814au: force USB 3.0?

### ISSUE THREAD

**Issue by i0ntempest** [chris1111/Wireless-USB-Big-Sur-Adapter#198]
These adapters can supposedly switch mode when connected to a supported WiFi network, but using this driver my 8814au based card stucks at USB 2.0 mode forever regardless of what network I connect to. Under Linux there's a way at driver level to force USB 3.0 on device initialization (https://askubuntu.com/questions/1189587/usb-3-0-and-3-1-are-recognized-as-2-0), is it possible with this driver?

**Comment by chris1111** [comment]
No only the[ Mediatek Drivers ](https://github.com/chris1111/D-LinkUtility-Package)support USB 3

**Comment by chris1111** [comment]
Mediatek is not Realtek
