### ISSUE TITLE
Uninstaller doesn't remove config.plist entry.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [chris1111/Wireless-USB-Big-Sur-Adapter#200]
and It causes can't boot after uninstall.
![20220407_104933](https://user-images.githubusercontent.com/7198776/162115634-fb36fc18-2c0a-44f1-909e-5ba04e788661.jpg)

**Comment by chris1111** [comment]
YES If you use [Wireless-USB-OC-Big-Sur-Adapter](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter)

**Comment by chris1111** [comment]
Wireless USB Big Sur Adapter not mount EFI partition because the kext's is not installed in EFI, its installed in /Library/Extensions/

**Comment by chris1111** [comment]
So use the good app for Uninstalling

**Comment by luceat-lux-vestra** [comment]
Thanks for your reply.

I've done uninstalling and working fine now.
And..., I was hoping to this may help this project and others.
Thanks for good project!
