### ISSUE TITLE
no usb wifi plug

### ISSUE THREAD

**Issue by zhujiacheng123** [chris1111/Wireless-USB-Big-Sur-Adapter#202]
When my applealc can work,wireless won't work.
But when my applealc ca n't work,it can use usb wifi

--My English is not good.

**Comment by chris1111** [comment]
USB Wifi as nothing to do with AppleAlc, check your setting.

**Comment by zhujiacheng123** [comment]
ok

**Comment by zhujiacheng123** [comment]
I think applealc can make usb wifi not work
I tired again.

**Comment by chris1111** [comment]
[delete](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/203)
