### ISSUE TITLE
No usb wifi plug

### ISSUE THREAD

**Issue by zhujiacheng123** [chris1111/Wireless-USB-Big-Sur-Adapter#203]
I tried again.
My usb wifi is realtek 8811cu.
When the alcid is 57 or 14 (AppleAlc working),The usb wifi adapter cannot work.
But the alcid can't make applealc work,usb wifi can find.
I think applealc can make usb wifi not work
Could you solve it？

[config.zip](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/8549193/config.zip)

**Comment by zhujiacheng123** [comment]
![image](https://user-images.githubusercontent.com/70752921/164965160-3e215e75-8cb4-4a3e-a08b-fa3d5cb8f1d9.png)

**Comment by chris1111** [comment]
USB Wifi as nothing to do with AppleAlc, check your setting, sorry but the program is not here to solved the hackintosh world
