### ISSUE TITLE
No download speed data

### ISSUE THREAD

**Issue by SH-M** [chris1111/Wireless-USB-Big-Sur-Adapter#21]
Hi,
Everything works fine except that it doesn't seem to give out the download speed, whereas the upload speed works fine. Just a minor quirk, thank you for making this 😄 

EDIMAX EW-7811Un (N150)

![Screenshot 2020-11-13 at 13 49 31](https://user-images.githubusercontent.com/15609236/99045307-22eafb00-25b7-11eb-8291-01b7e99c7c06.png)

**Comment by chris1111** [comment]
I don't know why?
