### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by SmartBoy84** [chris1111/Wireless-USB-Big-Sur-Adapter#212]
Could you please opensource the code for at least your installer? What drivers are you using here exactly, where have you gotten them, what did you do to make them work?

**Comment by chris1111** [comment]
There is no Source 
[No source](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/209)

**Comment by chris1111** [comment]
> Could you please opensource the code for at least your installer? What drivers are you using here exactly, where have you gotten them, what did you do to make them work?

IAM a Packager so it's easy to me repackaging with the good script
