### ISSUE TITLE
Wifi: on mac 12.x M1 Realtek 100$ or € reward ;-)

### ISSUE THREAD

**Issue by Tobias-Conrad** [chris1111/Wireless-USB-Big-Sur-Adapter#216]
Hello @chris1111,
it is a niche, of supporting a second WIFI on mac, you are filling nicely.
I followed your instructions, deactivated ... and reboot and after looking into the settings Missing: 3rd - Authorize the “Realtek Semiconductor Corp” device by clicking on “Allow”.
in system profile it shows the adapter

`802.11n NIC :

  Produkt-ID:	0x818b
  Hersteller-ID:	0x0bda  (Realtek Semiconductor Corp.)
  Version:	2.00
  Seriennummer:	00e04c000001
  Geschwindigkeit:	Bis zu 480 MBit/s
  Hersteller:	Realtek 
  Standort-ID:	0x01100000 / 1
  Verfügbare Stromstärke (mA):	500
  Erforderliche Stromstärke (mA):	500
  Zusätzlicher Betriebsstrom (mA):	0
`
see all also in the screencast please https://somup.com/c3irFIuOle

Best regards from Panama where two internet connections are needed at the same time ;-)

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/151
