### ISSUE TITLE
Odd Possible Bug BigSur and TPlink tl-wn822n v3

### ISSUE THREAD

**Issue by ashaikh** [chris1111/Wireless-USB-Big-Sur-Adapter#217]
I followed your instructions and was able to get the driver installed. I was able in the Big Sur Menu Bar to turn on USB-Wifi via the icon but for some reason I do not see it in network preferences as a USB Adapter on Big Sur. 

I can connect to my phone wifi via tethering but I can't see my home wifi 6 AX network. I can't even see any of my home 2.4 GHZ, 5 GHZ, 6 GHZ bands home SSIDs but I do see other networks around me (WPA2 Personal). 

CSRUTIL was disabled and is confirmed from the recovery console. 

Would you like screenshots?

**Comment by chris1111** [comment]
do you have a mac or Hackintosh?
