### ISSUE TITLE
Uninstall Fails

### ISSUE THREAD

**Issue by DeanMultimedia** [chris1111/Wireless-USB-Big-Sur-Adapter#221]
Monterey here.

I'd like to uninstall. When I hold "option" and click the menu icon, then "Uninstall USB-Wifi text" ... an alert box opens. I select "Yes".

Then NOTHING happens.

**Comment by chris1111** [comment]
Uninstall is from the Program, we have two Options  Install or Uninstall

**Comment by DeanMultimedia** [comment]
If you mean the .zip installation file's installer script, all that happens there is I receive a SIP notification and then it shuts down.

I did successfully install it but now SIP is re-enabled and I wish to uninstall.

What's the process?

**Comment by chris1111** [comment]
you need disable SIP like before to uninstall
