### ISSUE TITLE
Question Regarding Support : TP Link Archer T2U Nano

### ISSUE THREAD

**Issue by Doodle-Aks** [chris1111/Wireless-USB-Big-Sur-Adapter#223]
Hello, 

The following URL, https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter, lists TP Link Archer T2U Nano as a supported device. However, there are two other links listed in this Repo's Description, one for OC & the other for Clover. 

Under Both those URLs (For OC & Clover), TP Link Archer T2U Nano is not a part of Compatible/Known Working Devices. 

Could you help me understand what the differences are between "Wireless USB Big Sur Adapter" &  "Wireless-USB-OC-Big-Sur-Adapter" are and why Archer T2U Nano is not available in the latter ? 

Could you also let me know if I could use the Release Drivers from this repo with my hackintosh build ?
I'm planning on updating to macOS Monterey and was hoping to get Wi-Fi working with my Archer T2U Nano.

My Current Hackintosh Build Spec:
- RazerBlade Pro 17 (2019)
    - i7 9750H, 32GB DDR4 Ram, UHD 630 Graphics, Intel AX200 (Not working with macOS)
    - macOS Catalina (10.15.7)
    - Opencore Version : 0.8.3 
    
 Hope to hear from you soon. Thank you.

**Comment by chris1111** [comment]
Hello @Doodle-Aks 
if it has not been added to the list of functional adapters, it is simply an oversight on my part. I will add to the working list
Maybe after updating you have to Uninstall then reinstall the utility if its not work properly
