### ISSUE TITLE
How do you port drivers?

### ISSUE THREAD

**Issue by SmartBoy84** [chris1111/Wireless-USB-Big-Sur-Adapter#229]
What your process for getting drivers released for older versions of Mac OS to work on newer ones? For example, I'd like to get [this](https://support.dlink.com.au/Download/download.aspx?product=DWA-131&type=Drivers) to work, would it be possible?

**Comment by chris1111** [comment]
[Wireless USB Big Sur Adapter](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter) support DWA-131_E1 from macOS 11 to macOS 13

**Comment by chris1111** [comment]
The drivers are compatible for new Macs, they are original, the only thing is that the pre and postinstall script had to be adapted to be properly accepted.
