### ISSUE TITLE
System extension blocked problem

### ISSUE THREAD

**Issue by markjo2000** [chris1111/Wireless-USB-Big-Sur-Adapter#231]
![Screenshot 2022-10-12 at 22 02 45](https://user-images.githubusercontent.com/115844501/195950070-274e456d-9dd8-433a-acd1-aec65defec74.png)
Hi there.  I was using TP Link AC600/ Archer T2U Nano with TP link Catalina driver successfully, using Open Core Legacy Patcher on a couple of Macbook 5,1, as inbuilt wifi becomes unreliable above Mojave.

I've recently tried to fresh install my Macbooks to Big Sur 11.7 (using OCLP), and tried using your driver, but have repeated problems with the install. SIP and Gatekeeper seem to be successfully disabled following instructions, but the Realtek driver still wont install. Message is "System Extension Blocked... need to be updated by the developer"  Am I missing something, or is 11.7 the problem?  
Many thanks for any suggestions

**Comment by chris1111** [comment]
Uninstall this version then use the [OpenCore Version](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter)
