### ISSUE TITLE
TP-Link AC1300

### ISSUE THREAD

**Issue by DanielRomanMartinez** [chris1111/Wireless-USB-Big-Sur-Adapter#237]
As Chris1111 said, my previous "post" / "thread" in discussions is a issue.

https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/236#discussioncomment-3927926

So, i think that must be here, if I am wrong just tell me. Sorry for all problems i can cause.

**Problem**

I've installed correctly the drivers and I can connect with some wifi networks but can't use the internet.

This is not about my computer, because with the wifi i can use internet correctly, but not with the tp-link device.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/13299754/197044475-6110d1e8-d6ba-4f3a-81bc-5d4b5494a60d.png">

**Specs:**

- OS: Mac OS Monterey 12.6
- Computer: MacBook Pro (16-inch, 2019)

**Version Installed**

Wireless USB Big Sur Adapter-V14 : https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/releases/tag/V14

**Note**

I've seen also the the video that Chris posted (https://www.youtube.com/watch?v=YqZAy8jntow) 

And I think that i didn't miss a step.

**EDIT:** Added version installed

**Comment by chris1111** [comment]
I have the same adapter and its work from 10.15 to macOS 13 without any issue

**Comment by DanielRomanMartinez** [comment]
Hello chris, I 've seen your previous answer. And i couldn't contest.

It's possible that i am missing some command in terminal or disable something? 

Can I execute some command and help you to figure out what is happening?

**Comment by DanielRomanMartinez** [comment]
Finally seems like the network must be configured manually. DHCP doesn't work properly.

Also I think that public networks that requires to accept some permissions won't work properly. I will keep investigating, and i will attach here the results.

I think that i can close it anyway, are you agree ? @chris1111
