### ISSUE TITLE
Edimax EW-7822ULC not detected

### ISSUE THREAD

**Issue by jeremybeny** [chris1111/Wireless-USB-Big-Sur-Adapter#24]
hi on my Mac with Big Sur my usb dongle is not detected one the network preferences. I have the little icon with the dongle and a Red Cross on it. is there a way to make it work? thx

**Comment by jeremybeny** [comment]
I tried the #6 and #10 post answers by enabling disabling sip and gatekeeper but still not working

**Comment by chris1111** [comment]
EW-7822ULC its a known working adapter, it is already test and is support

**Comment by jeremybeny** [comment]
then maybe something went wrong during the install I uninstalled it restarted one recovery , enabled the sip restarded disable the sip installed it and I don't have the realtek option in the system preference, can you help me find were is the problem ? thank you

**Comment by chris1111** [comment]
Reset NVRAM
Disable SIP

**Comment by jeremybeny** [comment]
thnx will try
