### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Gizmo12344** [chris1111/Wireless-USB-Big-Sur-Adapter#240]
The Big Sur would crash my entire MacBook. Several weeks before it was working perfectly, until now. It would randomly crash my entire computer whenever I would enter the adapter, Why is that? First I would connect it and then the adapter would blink super fast rather than slowly. Then It would cause the entire thing to just freeze after 5 minutes of use. Please help, thank you for your consideration.

**Comment by chris1111** [comment]
The adapter as nothing to do with a crashing or anything else issue of crashing is on you side

**Comment by lycaeides** [comment]
> The Big Sur would crash my entire MacBook. Several weeks before it was working perfectly, until now. It would randomly crash my entire computer whenever I would enter the adapter, Why is that? First I would connect it and then the adapter would blink super fast rather than slowly. Then It would cause the entire thing to just freeze after 5 minutes of use. Please help, thank you for your consideration.

Did you solve it ?
