### ISSUE TITLE
can't execute the command /usr/sbin/spctl kext-consent add ZYM2ETK3E7 says spetl: failed to store new configuration.

### ISSUE THREAD

**Issue by HDV998** [chris1111/Wireless-USB-Big-Sur-Adapter#242]
hi, I had version 13 on Monterey and It worked great until I upgraded to Ventura, It said that the app was damaged and moved It to the bin. then I downloaded the version 14, disabled SIP, installed it and then when I reenabled SIP, it caused the same issue. then I realised that I forgot to run the command "/usr/sbin/spctl kext-consent add ZYM2ETK3E7" so I disabled SIP, uninstalled it and ran the terminal command but it gave this error "spetl: failed to store new configuration." what to do, please help

**Comment by HDV998** [comment]
Also I am using opencore 0.8.5

**Comment by chris1111** [comment]
spctl kext-consent disable
spctl kext-consent list

**Comment by HDV998** [comment]
![Screenshot 2022-10-26 at 8 17 44 AM](https://user-images.githubusercontent.com/91041845/197918954-b89dfe21-ca25-4c17-88e8-e50645ccf29e.png)
still doesn't work, same error when writing the spctl kext-consent disable command as well
