### ISSUE TITLE
Macos Ventura

### ISSUE THREAD

**Issue by SharkiArthur** [chris1111/Wireless-USB-Big-Sur-Adapter#245]
Hi, looking for support on MacOS Ventura, I've disabled SIP, and used your program, no luck, yes I saw it doesn't support m1 but still.. I have a M1 Air 2020. I have a 
Archer T2U Plus. 

Thanks
-Arthur

**Comment by chris1111** [comment]
it does not work on Mac M1 Apple chip

**Comment by SharkiArthur** [comment]
Alright, thanks.

**Comment by ahammedmishal** [comment]
> Alright, thanks.

did u find a way ?
