### ISSUE TITLE
No more WPA2 Enterprise invalid certificate popup

### ISSUE THREAD

**Issue by gz19880228** [chris1111/Wireless-USB-Big-Sur-Adapter#246]
I'm really sorry to bother with your work but I can't find my problem by searching.

I used to be on Catalina and your software worked perfectly.

But since I reinstalled macOS 12 and your updated adapter software, I can no longer connect to the exact same WiFi network.

The network uses WPA2 Enterprise encryption. After entering my name and password, there should be a popup window telling me the network has an invalid certificate. And I can choose to ignore the problem and continue.

But now with the new software the popup no longer shows up and I can't join the network anymore.

Is there possibly a way to tell the driver to always ignore certificate problems? I know this is dangerous, but I failed to get my boss to buy a proper license :(

Connecting to normal WPA2 Personal network works perfectly just like before.

macOS 12.6.1 OC hackintosh
V14 driver software, installed by the new SIP consent method
RTL8811AU that used to work perfectly in Catalina

Thanks.

**Comment by chris1111** [comment]
Its a known issue with macOS 11, 12 and 13
