### ISSUE TITLE
No USB-Wifi plug in

### ISSUE THREAD

**Issue by YawarOsman** [chris1111/Wireless-USB-Big-Sur-Adapter#247]
I have alpha adapter (AWUS036NH) and when i connect it to my MacOS ( Big Sur 11.7.1 ) it shows the adapter in the system information. i also downloaded the this package but it show this message `No USB-Wifi plug in`

i don't know what is the problem and i searched a lot and tried a lot of  ways but non of them worked

**Comment by chris1111** [comment]
Please Read the page AWUS036NH work with [Mediatek Drivers](https://github.com/chris1111/D-LinkUtility-Package)
