### ISSUE TITLE
No USB Plug in

### ISSUE THREAD

**Issue by PK268** [chris1111/Wireless-USB-Big-Sur-Adapter#250]
Hey, sorry for this because this is probably like the thousandth no usb plug in issue you've seen but I have an ALFA AWUS1900 and i can't get the adapter to work. Here's what I've already done:

Disable SIP
Uninstall and then reinstall adapter
Different USB port

**Comment by chris1111** [comment]
what machine are you trying this on?

**Comment by PK268** [comment]
Macbook pro 2019 16" intel i9

**Comment by chris1111** [comment]
> Macbook pro 2019 16" intel i9



Try this please [Wireless USB Big Sur Adapter-V15-1.zip](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/10135775/Wireless.USB.Big.Sur.Adapter-V15-1.zip)

**Comment by PK268** [comment]
Sorry, it still says no USB plug in

**Comment by chris1111** [comment]
So its not support for macOS 11,12,13
