### ISSUE TITLE
Only few seconds of fully working

### ISSUE THREAD

**Issue by ru379** [chris1111/Wireless-USB-Big-Sur-Adapter#253]
I have a TP-Link TL-WN8200ND usb adapter which is not listed in the supported models list but has the same chip than a supported one. The problem is that the drivers are installed correctly and wifi works good but after a few seconds it stops working although it is connected to the wifi and in macOS Settings shows that the adapter is working. For example in safari, the loading bar of the webpages stucks at a cuarter moreless and it doesn't do anything else.
Thanks in advance for the help.

**Comment by chris1111** [comment]
this is strange, try diferent usb port
