### ISSUE TITLE
Ventura 13.1 Seems to Have Broken Something

### ISSUE THREAD

**Issue by KershnerL** [chris1111/Wireless-USB-Big-Sur-Adapter#254]
I just got the Alfa AWUS 1900 last week, installed your package, everything was great (well, almost - more on that in the PS)! I could connect to my router, everything stable, awesome. (So you can add that adapter to the working list).

This morning, I upgraded to Ventura 13.1 and now the adapter is not working. I realize this is a 'my problem' because clearly state Ventura 13 and don't upgrade, but I thought maybe I could supply testing if you plan to update and if that would be helpful.
I can see the adapter in System Information>Hardware>USB, the IORegistry Log shows the adapter info and looks fine (I didn't get a copy of this Log while it was functioning to compare to, so I can't be sure everything's the same); but the adapter isn't powering on (no LED), it's not showing up in the System Settings>Network (this shows "Not Connected"), icon bar shows "No USB Plug-WiFi Plug in".

PS - The only gripe I had prior to my mistake of upgrading the OS was that my Macbook was not recognizing the adapter as a "Wi-Fi" or "Airport" interface, so I couldn't manage the adapter with the Airport command in Terminal. This is the first adapter I've tried, so I don't know if that's an Apple thing or a driver thing or something else.

**Comment by chris1111** [comment]
If you have update you have to Uninstall thene Reinstall utility
