### ISSUE TITLE
netgear a6210 support

### ISSUE THREAD

**Issue by 8o5** [chris1111/Wireless-USB-Big-Sur-Adapter#256]
Is the NETGEAR A6210 going to be added in the future?

**Comment by chris1111** [comment]
Its a Mediatek Drivers, try this utility then let me know if that work for you
[D-LinkUtility-Package](https://github.com/chris1111/D-LinkUtility-Package)

**Comment by 8o5** [comment]
Apologies if it's off topic, but I'm mainly trying to get this to work on a Kali Linux VM in UTM. Would installing those drivers and getting it running on my macbook allow me to use it in Kali?

**Comment by chris1111** [comment]
No the drivers is for macOS
