### ISSUE TITLE
No USB-WiFi Plug In

### ISSUE THREAD

**Issue by VinaWang** [chris1111/Wireless-USB-Big-Sur-Adapter#259]
Hi,
I just tried this on my MacBook Pro M1, it just shows "no usb-wifi plug in". I use archer t2u nano and ac600 and have already disable the sip. I also uninstall then reinstall it. But still can not work. Could you please help me with this? 

Thank you!

**Comment by chris1111** [comment]
Please read the page
[it-does-not-work-on-mac-m1](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter#it-seems-that-it-does-not-work-on-mac-m1-apple-chip-working-only-for-mac-intel)
