### ISSUE TITLE
Not working with Big Sur 11.0.1

### ISSUE THREAD

**Issue by CharlieBrown1-2** [chris1111/Wireless-USB-Big-Sur-Adapter#26]
I have installed and reinstalled package on MacOS Big Sur 11.0.1, disbaled SIP, allowed the realtek semiconductor, still does not work. Am I just missing something

**Comment by chris1111** [comment]
maybe plug the USB adapter ? or see if the brand are compatible

**Comment by CharlieBrown1-2** [comment]
I’m using net gear nighthawk ac1900 A7000, have tried every port. With
powered usb hub and without one.

On a MacBook Pro 16in 2019
