### ISSUE TITLE
With SIP enable

### ISSUE THREAD

**Issue by Rxxbertx** [chris1111/Wireless-USB-Big-Sur-Adapter#261]
I've been doing the same process 5 times and it doesn't work with SIP enable OC hackintosh

**Comment by chris1111** [comment]
you did something wrong because it works, I have tested everything from Big Sur 11 to Ventura 13

**Comment by Rxxbertx** [comment]
I have carried out the phase of having the SPI active, then execute Consent.command, reboot in recovery And put SIP disable and /use.....kext-consent add.... I have rebooted, I have installed the wifi adapter I opened the config.plist file to make an OC clean Snapshot, I have rebooted, I have connected to the wifi network, I have rebooted in recovery and put SIP ENABLE, I have rebooted and the app disappears saying That there has been a problem with the app :/

**Comment by Rxxbertx** [comment]
MacOS: Ventura 13 with OPENCORE

**Comment by Rxxbertx** [comment]
Okey, i found the problem... U need to open settings , privacy. And allows statusappbar.... (I have disable spctl.. and still ask for permission to open it)
