### ISSUE TITLE
Netgear A8000 Support

### ISSUE THREAD

**Issue by cluelessdev404** [chris1111/Wireless-USB-Big-Sur-Adapter#262]
Adapter Device: Model Number A8000 Netgear Wireless Adapter
OS: macOS 13.2.1 Ventura

**Comment by chris1111** [comment]
What?

**Comment by cluelessdev404** [comment]
Yeah that's the Windows driver, there's no macOS one. I

**Comment by chris1111** [comment]
> Yeah that's the Windows driver, there's no macOS one. I


I known no mac Drivers available  😄 then probably never
