### ISSUE TITLE
MacOS Ventura complains the StatusBarApp.app is damaged, thus cannot open

### ISSUE THREAD

**Issue by cc2lee** [chris1111/Wireless-USB-Big-Sur-Adapter#266]
After successful installation on MacOS 13 (Ventura), root the Mac and the MacOS pops up a dialog, saying the StatusBarApp.app is damaged and needs to be moved into Trash Bin.

Update: It works fine when SIP is disabled. The error occurs when SIP is enabled.

**Comment by b0bd** [comment]
same issue on 13.3.1.   Using OpenCore 0.9.1 and the OC installer.   StatusBarApp.app is damaged, unless csrutil disable is run.

It did work on Monterey with the kext-consent command, but that doesn't work on Ventura.

**Comment by chris1111** [comment]
> same issue on 13.3.1. Using OpenCore 0.9.1 and the OC installer. StatusBarApp.app is damaged, unless csrutil disable is run.
> 
> It did work on Monterey with the kext-consent command, but that doesn't work on Ventura.

Of course not working with OCLP
This program work perfectly if you know what you did even with OCLP
