### ISSUE TITLE
Doesn't work on Big Sur 11.0.1

### ISSUE THREAD

**Issue by arutkayb** [chris1111/Wireless-USB-Big-Sur-Adapter#27]
Now, I've no internet on my Macbook pro mid 2015 Big Sur 11.0.1 :/

**Comment by chris1111** [comment]
MR What is your adapter

**Comment by arutkayb** [comment]
I didn't try disabling sip and fixed the mac's own wifi interface. Since it is the case, I couldn't try to your driver by following all the steps including disabling the sip. So, I'm closing the issue. Thanks.
