### ISSUE TITLE
RtWlanU.kext causes a bug with Display scales.

### ISSUE THREAD

**Issue by erdengurkan** [chris1111/Wireless-USB-Big-Sur-Adapter#28]
I'm using r5 3600 OC rx580 Bigsur 11.0.1

After I install this pkg, when I change display scales pc lagging so bad. Reverting back doesnt help, CPU levels doesnt effected still over 80% free but its not usable.

I tested 3 added kexts other 2 is ok but RtWlanU.kext causes this issue. Without it my card doesnt work.

Same issue also happens with Catalina but Majove is ok 

Please let me know if this is ok with your setup

Thank you!

**Comment by chris1111** [comment]
Sorry but this is non sense
the package install 2 kext for Wifi and its work good since the first Beta, please don't post a Hackintosh issue on this project
