### ISSUE TITLE
unable to join PEAP 

### ISSUE THREAD

**Issue by chteow** [chris1111/Wireless-USB-Big-Sur-Adapter#281]
how to find the log to figure out what's wrong with trying connecting to peap network ? 
It just keep spinning

**Comment by chris1111** [comment]
There are no logs that can be extracted directly from the app, try to see through the console
Anyway there is no PEAP
![Screenshot 2023-07-11 at 06 06 01](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/6248794/3ca7e9e9-fe7e-438a-9407-55a578a06c76)
