### ISSUE TITLE
Doesn't work with Realtek 0xf179 on Ventura

### ISSUE THREAD

**Issue by egslava** [chris1111/Wireless-USB-Big-Sur-Adapter#282]
Hello! Thank you for doing this amazing stuff! I didn't believe I would be able to find these drivers, to be honest (◕‿◕)

Today I bought realtek 0xf179 wi-fi adapter and tried to make it work (`csrutil disable` in safe mode and, later, in normal mode, sudo spctl --master-disable)  on macos ventura (13.4 (22F66), mbp 2018), but it says, that there's no wi-fi adapter.

Specifications:

```
>         802.11n:
> 
>           Product ID: 0xf179
>           Vendor ID: 0x0bda  (Realtek Semiconductor Corp.)
>           Version: 0.00
>           Serial Number: 90DE808DCCA9
>           Speed: Up to 480 Mb/s
>           Manufacturer: Realtek
>           Location ID: 0x14100000 / 7
>           Current Available (mA): 500
>           Current Required (mA): 500
>           Extra Operating Current (mA): 0
```

What could go wrong?

<img width="328" alt="Screenshot 2023-08-05 at 11 01 45 PM" src="https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/1143228/4d702ea6-8cf8-4308-b727-3ac439b3293a">

**Comment by chris1111** [comment]
What brand and model of USB adapter are you using? Without that I can't help you

**Comment by egslava** [comment]
Thank you for your reply. What do you mean by brand and model? I thought, "realtek 0xf179" would be enough, but I'm not familiar much with chips/electric engineering or drivers.

Here I found the photo of the package in the internet:
<img width="659" alt="Monosnap i-rock wifi - Google Search 2023-08-08 09-46-20" src="https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/1143228/67978c2d-2a1c-49aa-a950-4bc4f189f626">

So the brand is "i-rock". When I tried to find 'realtek 0xf179 brand name', I found "RTL8188FTV" in this issue ([102](https://github.com/chris1111/Wireless-USB-Adapter/issues/102)) in this repo, lol. Basically, it ends up, that this wi-fi adapter is not supported (◕‿◕)

Anyways, thank you for your time!

**Comment by chris1111** [comment]
Exactly not supported
