### ISSUE TITLE
TL-WN725N isn’t detected on macOS Monterey 

### ISSUE THREAD

**Issue by Mooshaah** [chris1111/Wireless-USB-Big-Sur-Adapter#287]
After doing the setup and checking the Kexts are there and enabled , and making sure everything is good the program produces the message: No USB WiFi plug in .

**Comment by chris1111** [comment]
Only the V3 of TL-WN725N works so check your adapter if it's a V3

**Comment by Mooshaah** [comment]
it's V3 and EU

**Comment by chris1111** [comment]
what model of mac your are using this?

**Comment by Mooshaah** [comment]
Mac os 12 (Montrey)

**Comment by chris1111** [comment]
what model is your mac

**Comment by Mooshaah** [comment]
It's a hackintosh not a mac

**Comment by chris1111** [comment]
why using the program more dedicated for Mac if you have a Hackintosh? did you read the page

**Comment by Mooshaah** [comment]
No actually i didnt pay attention to it as i found the repo link on YT,  and in the videos your program was used on hackintoshs, so it won't work right?
