### ISSUE TITLE
Wifi indicator blacked out

### ISSUE THREAD

**Issue by BlackhawkDown2002** [chris1111/Wireless-USB-Big-Sur-Adapter#29]
Hello, everything installed perfectly when I followed the instructions. Installed on a Macbook Pro (2017) running Big Sur. However, the Wifi indicator for the Archer T2U device is blacked out instead of white so I cannot tell when I am actually connected or not.

**Comment by chris1111** [comment]
See a temporary fix 
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/releases/tag/V6
