### ISSUE TITLE
Driver not working macOS Sonoma

### ISSUE THREAD

**Issue by dennis777** [chris1111/Wireless-USB-Big-Sur-Adapter#290]
The driver does not seem to work on macOS Sonoma.

macOS Sonoma 14.0, M1 Max 14" MacBook Pro

I followed [this](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/160) guide, and after installing and reenabling `csrutil` the application does not detect my Alfa AWUS036ACH it says No wifi USB plugin
<img width="319" alt="image" src="https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/25965937/1ae6a4b5-2764-4d23-9c0a-e6ddf21ccd0c">

And the light on the Alfa does not light up
![IMG_3814](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/25965937/eb89f608-941b-47d4-96ba-43e00c231cb1)

I tested the Alfa on my kali linux machine and it worked so the issue is not the network adaptor.

What could be the issue?

**Comment by chris1111** [comment]
It does not work on Apple Chip
