### ISSUE TITLE
USB Adapter not active after Big Sur installation

### ISSUE THREAD

**Issue by chris1111** [chris1111/Wireless-USB-Big-Sur-Adapter#291]
### Discussed in https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **Augeydoggy** September 20, 2023</sup>
I installed the Big Sur drivers on my 2015 Macbook Pro running Monterey 12.6. I disabled the SIP, gave the necessary permissions, and it said it had installed. I am using a Netgear A6150, which now shows up in the network preferences, but as not connected. I am not a programmer, but all the steps seemed to have gone correctly, so don't know what to do next. </div>

**Comment by Augeydoggy** [comment]
Somehow after the most recent Monterey update the A6150 is now connected. However I still cannot get the wifi turned on:
![Screen Shot 2023-09-22 at 2 51 37 PM](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/145621033/e3275f09-08cd-45eb-91cd-c3bcd3c10ad1)

**Comment by Augeydoggy** [comment]
After updating to Monterey 12.7, the A6150 suddenly connected. But I still cannot get the WiFi started:

![Screen Shot 2023-09-22 at 2 51 37 PM](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/145621033/edf26510-f551-463d-83e7-93bb78f8fc03)

**Comment by chris1111** [comment]
![270035402-edf26510-f551-463d-83e7-93bb78f8fc03](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/6248794/e49cb98e-0d8c-4f59-aa44-3f3feb846cd9)

**Comment by Augeydoggy** [comment]
Doh! It's working now, tho it took a few tries to actually connect to our
network. THANKS!
