### ISSUE TITLE
Netgear A8000 mt7921 support

### ISSUE THREAD

**Issue by Dominua** [chris1111/Wireless-USB-Big-Sur-Adapter#296]
Hello! do you planning to add supporting Netgear A8000 mt7921? Or it is not possible atm?

**Comment by FarParticular** [comment]
it has a chip from mediatek, in the beginning he wrote that mediatek is not supported, so it will not work.

**Comment by Dominua** [comment]
> it has a chip from mediatek, in the beginning he wrote that mediatek is not supported, so it will not work.

Miss that. Thank you.
