### ISSUE TITLE
Wifi File Sharing and Location Services

### ISSUE THREAD

**Issue by czuszuw** [chris1111/Wireless-USB-Big-Sur-Adapter#297]
Is there any way to enable wifi file sharing similar to airdrop or to enable location services. I have archer t3u dongle and i cant connect to any other device to send files wirelessly. Moreover apps like siri and maps cant determine my location despite allowing it in privacy section

**Comment by chris1111** [comment]
No way to enable AppleService with this kind of app, you need using third party app do doing this
