### ISSUE TITLE
System Extension blocked

### ISSUE THREAD

**Issue by filipopo** [chris1111/Wireless-USB-Big-Sur-Adapter#298]
I'm using MacOS 14.1.2 on a M1 pro macbook and I got this message during install
<img width="292" alt="Screenshot 2023-12-22 at 18 19 31" src="https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/4060824/1c151ecb-b574-4f83-bd8d-4dc9e96b9de0">
....... I just read that it doesn't work on Apple Silicone .... is this the reason the system extensions are blocked?

And is there something we can do to make it run on M1, M2, M3, ... maybe even file a bug report to apple? I don't know which USB Wifi dongle to get if this doesn't work on M1 Mac...

**Comment by chris1111** [comment]
It does not work on Apple Chip

**Comment by filipopo** [comment]
You are very helpful, maybe the problem is not in the apple chip and also your repo will die out because no new hardware is made without an apple chip

**Comment by chris1111** [comment]
> You are very helpful, maybe the problem is not in the apple chip and also your repo will die out because no new hardware is made on intel chips

You are Wrong ☛ [OCLP](https://github.com/dortania/OpenCore-Legacy-Patcher/)

**Comment by filipopo** [comment]
So you will forever use 2007 hardware? okay man whatever
