### ISSUE TITLE
Please make a version that is compatible with OpenCore since now kext injection is working on OpenCore 0.6.0

### ISSUE THREAD

**Issue by ManasMalla** [chris1111/Wireless-USB-Big-Sur-Adapter#3]
I would also like to quote that the kext file which works on Clover can be added and copied to open core EFI and config.plist to work on open core.

**Comment by chris1111** [comment]
Try

**Comment by ManasMalla** [comment]
I was able to get Wifi USB adapter by install THE WIRELESS USB adapter for macOS previous version and adding kexts to opencore and it s config.plist

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
