### ISSUE TITLE
MacOS 13.3.1 not recognising awus1900

### ISSUE THREAD

**Issue by eXe2902** [chris1111/Wireless-USB-Big-Sur-Adapter#301]
I have a 2019 intel macbook pro and after installing everything and plugging in the adapter, it is not recognised, any ideas?

**Comment by eXe2902** [comment]
It gets recognised in the system information as  802.11ac NIC

**Comment by eXe2902** [comment]
am stupid and skipped the last step in installation, works now

**Comment by chris1111** [comment]
> am stupid and skipped the last step in installation, works now

Don't be too hard on yourself, these things happen but you're not stupid
