### ISSUE TITLE
No USB-WiFi plug in

### ISSUE THREAD

**Issue by beckzhao0410** [chris1111/Wireless-USB-Big-Sur-Adapter#305]
macOS Monterey 12.6.9
Already disable SIP
Installed the Wireless USB OC Big Sur Adapter-V16 
Plug in my USB wifi, it is comfast CF-811AC V3 
Opencore config as blow:
![SCR-20240225-ppxq](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/62934437/a50e7703-62e7-44f9-a69a-1a13a979f57c)
But after I restart, usb wifi cannot use and hint "No USB-WiFi plug in"
![SCR-20240225-poiy](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/assets/62934437/0c97b72d-9764-474f-a1c0-d76e684f4507)
I don't know why has this issue

**Comment by chris1111** [comment]
Did you try differant USB port?

**Comment by beckzhao0410** [comment]
Yes, I tried all USB ports.
When I use "kextstat | grep -v "RtWlan" in Terminal, there is nothing. So, I think the kexts are not loaded successful.

**Comment by chris1111** [comment]
If is not load succesful from OC its probably a config issue? , check correctly

**Comment by beckzhao0410** [comment]
I am not sure, would it conflict with other config?

**Comment by beckzhao0410** [comment]
I changed another USB WiFi, this issue resolved
