### ISSUE TITLE
Support for WIFI & Bluetooth adapter (TP-LINK AC600 / Archer T2UB Nano)

### ISSUE THREAD

**Issue by gmorales254** [chris1111/Wireless-USB-Big-Sur-Adapter#308]
Hey there!

I just bought a USB Wifi & Bluetooth (all in one) adapter (model in the title), I also want to use the Bluetooth because I need it. It's possible to see a solution on there?

Thanks for all your contributions.

PSD: The wifi is working, just I cant see the bluetooth.

**Comment by chris1111** [comment]
Bluetooth from USB wifi never work in macOS you need another dongle compatible macOS with BlueToolFixup.kext

**Comment by gmorales254** [comment]
Thanks for your explanation, Chris!

**Comment by BlkDev9** [comment]
I'm using this dongle and Bluetooth works fine lol
