### ISSUE TITLE
Asus USB-AC51 support

### ISSUE THREAD

**Issue by EXPAWNEN** [chris1111/Wireless-USB-Big-Sur-Adapter#31]
Hello
I'm using OpenCore 0.6.3, macOS 11.0.1, SecureBoot and SIP are disabled, gatekeeper allows to run software from any developer but my USB-AC51 adapter doesn't work. I have seen that oldest adapter model that your driver supports is ASUS USB-AC53. My adapter AC51 supports 802.11ac standard and can I somehow make this adapter to work or there is no drivers to boot this ?

**Comment by chris1111** [comment]
USB-AC51 is not working here this is a Mediatek Drivers support by RT2870USBWirelessDriver. This drivers is not support in macOS since High Sierra
