### ISSUE TITLE
Failed to install on Mac os Sonoma 14.4.1 (23E224)

### ISSUE THREAD

**Issue by shimitapiro** [chris1111/Wireless-USB-Big-Sur-Adapter#314]
trying to install getting an error of not compatible

**Comment by chris1111** [comment]
tell me more about the error

**Comment by shimitapiro** [comment]
Don't see an error but a screen, anyway just saw this : It seems that it does not work on Mac M1, M2 Apple chip, working only for Mac Intel.

Is there any plan to support M2 ?

**Comment by chris1111** [comment]
No plan to support Apple chip
