### ISSUE TITLE
how to change mac adresse ???

### ISSUE THREAD

**Issue by kazundo** [chris1111/Wireless-USB-Big-Sur-Adapter#316]
I would like to change the Mac address of my Alfa but it tells me that your software does not support changing the Mac address!!!

**Comment by chris1111** [comment]
This has nothing to do with the program, I have to close this issue

**Comment by kazundo** [comment]
❯ sudo macchanger -r en6
Password:
ERROR:   Can't set MAC address on this device. Ensure the driver supports changing the MAC address.

**Comment by chris1111** [comment]
The driver use the ethernet mac address not the airport
[see
](https://www.guru99.com/mac-address-find-change.html)

**Comment by kazundo** [comment]
i dont work mac adress can be change !!!

❯ sudo openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'
2b:5b:1e:8c:50:31
❯ sudo ifconfig en6 ether 2b:5b:1e:8c:50:31
❯ sudo ifconfig en6 ether 2b:5b:1e:8c:50:31
❯ ifconfig en6
en6: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 00:c0:ca:a8:f7:ad
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (<unknown type>)
	status: inactive
