### ISSUE TITLE
Slow Wifi speeds with AC600 TP LINK T2U Nano

### ISSUE THREAD

**Issue by Techgeek2011** [chris1111/Wireless-USB-Big-Sur-Adapter#319]
this issue was plaguing me in sonoma, so i downgraded to ventura. the same issue occurs. and it occurs in usb 2 and 3 ports. please help, i am using latest V17

**Comment by chris1111** [comment]
were is the wifi speed test

**Comment by Techgeek2011** [comment]
Hi. So I did an Ookla speed test and got download speeds of 9mbps on Sonoma. On Ventura, the test won't even run.

**Comment by Techgeek2011** [comment]
Why did you close it? It's still not fixed.

**Comment by chris1111** [comment]
you have not produced a Wifi speed test request 
anyway your problem is  not relate with the drivers
