### ISSUE TITLE
Any way to support RTL8192FU?

### ISSUE THREAD

**Issue by eeneecha** [chris1111/Wireless-USB-Big-Sur-Adapter#323]
I found a driver from the manufacturer's website but the driver only supports up to Mojave.  [https://www.tendacn.com/download/detail-2911.html](url)

**Comment by chris1111** [comment]
Did you try [ Wireless-USB-Big-Sur-Adapter
 ](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter)

**Comment by eeneecha** [comment]
> Did you try [ Wireless-USB-Big-Sur-Adapter](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter)

Yes. I have tried it. It stays on "No usb wifi-plugin"

**Comment by chris1111** [comment]
> > Did you try [ Wireless-USB-Big-Sur-Adapter](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter)
> 
> Yes. I have tried it. It stays on "No usb wifi-plugin"


There is [no source for the Driver](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/discussions/209)
