### ISSUE TITLE
NO USB-WIFI PLUG IN - TPLINK WN823N V2.0

### ISSUE THREAD

**Issue by xingzj** [chris1111/Wireless-USB-Big-Sur-Adapter#337]
my wn823n v2.0 can't be found on my hackintosh macos 12 monterey, the message  no usb-wifi plug in was appeared, i check the driver and config.plist are correct because my another usb stick rtl 8822bu is correctly drivered and everything is ok, so is there any special step for the wn823n v2.0? thanks

**Comment by xingzj** [comment]
![1729310185987582582798111487253](https://github.com/user-attachments/assets/3c4037b5-1a40-4584-b66f-b86aa1324176)

**Comment by chris1111** [comment]
it's strange because I have the same wifi adapter but mine has a network search button on the other hand mine works very well and it's also the V2

![IMG_4289](https://github.com/user-attachments/assets/45e7f6e1-ad00-4577-a21a-5dcba1c4adbf)

**Comment by xingzj** [comment]
I see，so it should be vary version in defferent region, mine is mainland China，and it's no driver version, it would appeared as a optical drvier firstly in Win system and when the driver program was installed the optical driver will disappeared, and then the USB
Wifi Stick will be working

**Comment by chris1111** [comment]
I will close this issue at this time
