### ISSUE TITLE
TP - Link AC600 T2UB nano WiFi working but bluetooth is NOT (Sonoma).

### ISSUE THREAD

**Issue by Jyoti-Kabir** [chris1111/Wireless-USB-Big-Sur-Adapter#338]
I don't know what I did wrong. The adapter had an official driver for upto Catalina AFAIK, which doesn't work at all in my Sonoma. Can you please help how do I get the bluetooth working?

**Comment by chris1111** [comment]
Bluetooth only work in windows
For macOS you need a compatible dongle with the [appropriate kext](https://github.com/acidanthera/BrcmPatchRAM)
