### ISSUE TITLE
TP-Link TL-WN826N not working

### ISSUE THREAD

**Issue by Jacky-YC** [chris1111/Wireless-USB-Big-Sur-Adapter#340]
![image](https://github.com/user-attachments/assets/f35b34be-6075-4211-bf78-b95a71deb41f)

display `No USB-WIFI Plug in`

**Comment by chris1111** [comment]
I known its not onder [the list](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter?tab=readme-ov-file#%EF%B8%8E---known-working-and-testing-adapter)
thanks to repport
