### ISSUE TITLE
No USB-WiFi Plugin on Big Sur v11.1

### ISSUE THREAD

**Issue by UJPrasad** [chris1111/Wireless-USB-Big-Sur-Adapter#36]
<img width="327" alt="3" src="https://user-images.githubusercontent.com/21108887/102455657-f7e84100-4065-11eb-813b-d135204b71fa.png">

<img width="294" alt="4" src="https://user-images.githubusercontent.com/21108887/102455658-f880d780-4065-11eb-92e7-fa21b5d9f833.png">

<img width="466" alt="1" src="https://user-images.githubusercontent.com/21108887/102455650-f585e700-4065-11eb-8160-4e7cc4673246.png">
<img width="634" alt="2" src="https://user-images.githubusercontent.com/21108887/102455656-f6b71400-4065-11eb-91da-d4b82f9c1b66.png">

**Comment by chris1111** [comment]
Adapter brand?

**Comment by UJPrasad** [comment]
Hi, @chris1111 thanks for the immediate response.
Adapter brand -> TP-Link Archer T2U Nano
Big Sur Version -> 11.1 (20C69)

**Comment by chris1111** [comment]
> Hi, @chris1111 thanks for the immediate response.
> Adapter brand -> TP-Link Archer T2U Nano
> Big Sur Version -> 11.1 (20C69)

Archer T2U Nano is support and already test in BS
make sure the SIP is fully disable if you don't have A popup security for allowing extensions this is because SIP is not fully disable

**Comment by UJPrasad** [comment]
I have done this to fully disable SIP:

```
Restart your computer in Recovery mode.

Launch Terminal from the Utilities menu.

Run the command csrutil disable.

Restart your computer.
```


Do we need to do something else or this should work? Is there any other way rather than typing `csrutil status` to check if SIP is fully disabled?

**Comment by UJPrasad** [comment]
It's a real mac - MacBook Pro Model A1502.

**Comment by chris1111** [comment]
> It's a real mac - MacBook Pro Model A1502.

all my test and video is from the same MacBook Pro so you have a corruption problem or whatever?
try to uninstall the program reboot to the recovery HD enable the SIP reboot to your mac then reboot again in recovery HD disable the SIP and install the program
