### ISSUE TITLE
Try to make the driver recognised as internal wifi of macOS Big Sur

### ISSUE THREAD

**Issue by ManasMalla** [chris1111/Wireless-USB-Big-Sur-Adapter#4]
Try to make the driver recognised as internal wifi of macOS Big Sur so that the default wifi icon can be used to enable and connect to wifi instead of it being detected as ethernet adapter(en2) and a separate icon for wifi in the bar and the wireless utility.
Also my request is if possible add support of it as a kext that can be copied to the kext folder of the boot loader so that it can enabled even during the setup process instead of choosing this Mac doesn't connect to the network, enabling the setup of Apple ID and etc.
Hoping for a positive reply soon!
![Screenshot 2020-07-03 at 12 15 39 PM](https://user-images.githubusercontent.com/38750492/86439854-fbda0e00-bd26-11ea-9531-652aa69ce8d0.png)

**Comment by chris1111** [comment]
I have already do this
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
Default connection is Ethernet connection since Catalina so its not possible to change that
