### ISSUE TITLE
Mac cannot find location

### ISSUE THREAD

**Issue by evasilis** [chris1111/Wireless-USB-Big-Sur-Adapter#41]
Hi there

After installing the V5 and later the V7 drivers, big sur says that it cannot find location as there is no wifi. Would you have any suggestions?

Thanks for your time and work!
V

**Comment by chris1111** [comment]
> Hi there
> 
> After installing the V5 and later the V7 drivers, big sur says that it cannot find location as there is no wifi. Would you have any suggestions?
> 
> Thanks for your time and work!
> V

What is the adapter brand?

**Comment by evasilis** [comment]
Thanks for your reply! It is a tp-link Archer TU2 Plus connected via USB 2 to a 5,1 mac pro. =Big sur was installed the bigmac 1.1 method and it is unpatched.

Thanks a lot!

**Comment by chris1111** [comment]
It is really strange because Archer TU2 Plus is already test here  [Known Compability Adapter](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/18)

**Comment by chris1111** [comment]
Do you see this before reboot?

![Capture d’écran, le 2020-12-25 à 15 01 52](https://user-images.githubusercontent.com/6248794/103141440-56df3300-46c2-11eb-8c36-ad8c73cc1c36.png)

![Capture d’écran, le 2020-12-25 à 15 02 33](https://user-images.githubusercontent.com/6248794/103141444-5b0b5080-46c2-11eb-9abe-9fef2d2637e8.png)

**Comment by evasilis** [comment]
Yes and I allowed and then rebooted.

**Comment by chris1111** [comment]
> Yes and I allowed and then rebooted.

Try another USB port ?
Or
Try Uninstall the reboot then reinstall the program
 Let me known

**Comment by evasilis** [comment]
I will do that.

Thanks!

**Comment by evasilis** [comment]
I did uninstall - reboot - reinstall and also tried a different usb port but there was no change.

**Comment by evasilis** [comment]
Happy new year to you and yours!

**Comment by chris1111** [comment]
I wish you Happy New Year

![1f09688de2ff43835b3b287220405452 gif e66b7ee63cb33297033fa40e2b9d9119](https://user-images.githubusercontent.com/6248794/103439391-7dddbd80-4c0a-11eb-9fde-c463dd75e5e4.gif)
