### ISSUE TITLE
Add Cudy WU650

### ISSUE THREAD

**Issue by ninjacarlo** [chris1111/Wireless-USB-Big-Sur-Adapter#45]
Please add the Cudy WU650 wireless adapter to the support list, I've got this one and I really need it for work.

**Comment by chris1111** [comment]
this adapter not work on macOS

**Comment by ninjacarlo** [comment]
But it used to work till macos catalina 10.15!

Il mar 29 dic 2020, 12:30 chris1111 <notifications@github.com> ha scritto:

**Comment by chris1111** [comment]
> But it used to work till macos catalina 10.15! Il mar 29 dic 2020, 12:30 chris1111 <notifications@github.com> ha scritto:
> […](#)

Sorry yes its work follow the guide correctly

**Comment by ninjacarlo** [comment]
How to make the software in the upper bar auto-start at boot?
Is there a way to put it as a login item? (I'm on BigSur)

Il giorno mar 29 dic 2020 alle ore 13:05 chris1111 <notifications@github.com>
ha scritto:
