### ISSUE TITLE
After m1 macmini 11.1 disables sip, the installation can be successful, but the network card cannot be recognized

### ISSUE THREAD

**Issue by baipiaoing** [chris1111/Wireless-USB-Big-Sur-Adapter#48]
After m1 macmini 11.1 disables sip, the installation can be successful, but the network card cannot be recognized when the network card is inserted, and "No USB-WiFi Plug in" is still displayed. The network card is confast cf-811ac

**Comment by chris1111** [comment]
Why using Cheap USB adapter on M1 macMini with native WIFI

**Comment by baipiaoing** [comment]
At my school in China, the campus network requires authentication to log in. I want to use my computer to connect to wifi and open a hot spot

**Comment by chris1111** [comment]
I don't think Hot spot work with WIFI adapter but see this
Runing Intel app on Mac M1 chip
https://derflounder.wordpress.com/2020/11/17/installing-rosetta-2-on-apple-silicon-macs/

**Comment by baipiaoing** [comment]
I mean, I use this adapter to connect to Wi-Fi and use the built-in network card of the computer to open the hotspot.

**Comment by baipiaoing** [comment]
The previous computer did this in 10.15. Now after changing the computer, the first method can no longer be used.

**Comment by chris1111** [comment]
No way to do this on M1 chip

**Comment by baipiaoing** [comment]
thank you

**Comment by blairmacintyre** [comment]
is this likely to ever work on an M1 mac?

**Comment by chris1111** [comment]
> is this likely to ever work on an M1 mac?

not for now maybe in the futur when Realtek updated the Utility

**Comment by Tarmstrong95** [comment]
@chris1111 any update on this?
