### ISSUE TITLE
Failed to install on MacOS Big Sur 11.1(Apple M1)

### ISSUE THREAD

**Issue by JeffyLapter** [chris1111/Wireless-USB-Big-Sur-Adapter#56]
![image](https://user-images.githubusercontent.com/48401984/105571480-0b847700-5d8b-11eb-8819-48bcfa2e7fe7.png)
Unable to fit the newest MacOS Big Sur version..

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/48
