### ISSUE TITLE
Possible to re-enable SIP after installation on Big Sur?

### ISSUE THREAD

**Issue by jamescrowley** [chris1111/Wireless-USB-Big-Sur-Adapter#59]
I'm trying to install this on macOS Big Sur. When I was installing HoRNDIS (which had a similar issue) it was possible to disable SIP, install the extensions, and then re-enable it again (https://github.com/jwise/HoRNDIS/issues/132). 

Everything works fine with the v7 release of the Wireless USB adapters until I re-enable SIP, at which point I just see "no USB-WiFi plugin" and no green lights on the adapter. I tried running

`kextstat | grep -v com.apple`

and when SIP was disabled I get:

     135    0 0xffffff7fa2456000 0x2a3000   0x2a3000   com.realtek.driver.RtWlanU (1830.32.b20) A3E82AA7-B282-3667-BAAE-D23A304794F9 <66 46 6 5 3 1>

but it disappears when SIP has been enabled again. If I go and disable SIP again, it still doesn't work - I have to go through the installation process again.

Has anyone managed to achieve this? @chris1111 I see you suggest in https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/20 that you should be able to? Thanks

**Comment by chris1111** [comment]
The SIP need to stay disable
