### ISSUE TITLE
Not working on MacBook Pro (Retina, 13-inch, Late 2013) 

### ISSUE THREAD

**Issue by 4shadowr** [chris1111/Wireless-USB-Big-Sur-Adapter#6]
I followed your instructions from video
I get Installed Successfully, I restart
After restart the status bar icon says 
> No USB-WiFi Plugin

Where as I have the adapter plugged in and my usb slots are also working
Tried both Releases v1 & v2
[Installer Log 15-Jul-2020 v2.txt](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/4924365/Installer.Log.15-Jul-2020.v2.txt)

System:- 
Device: MacBook Pro (Retina, 13-inch, Late 2013)
OS version: 11.0 Beta (20A4300b)
Adapter: TL-WN725N

**Comment by chris1111** [comment]
What is the TL-WN725N ? If you have V1 and V2 no macOS driver for this adapter
https://www.tp-link.com/ca/support/download/tl-wn725n/
If you have the V3 that suppose to work if you have allow software from security ?
So uninstall then retry if you have V3 then let me know

**Comment by 4shadowr** [comment]
Its V3 and Yes, I have allowed it from 
> System Preferences -> Security & Privacy -> Allow Realtek

**Comment by chris1111** [comment]
> Its V3 and Yes, I have allowed it from
> 
> > System Preferences -> Security & Privacy -> Allow Realtek
> 
> It was working with [Wireless USB Adapter Clover-V15](https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/tag/V15)

I have the same MacBook of you and its work here 
https://support.apple.com/kb/sp691?locale=fr_CA

**Comment by 4shadowr** [comment]
It's Not working on My MBP,
I have uploaded the installer file if that helps
Any Idea on how to troubleshoot this?

**Comment by 4shadowr** [comment]
Which beta are you running?
I am on Latest Beta (11.0 Beta (20A4300b))
Have you tried it on that ?

**Comment by chris1111** [comment]
same

**Comment by chris1111** [comment]
When you have Allow soft did you see multiple Soft trying to allow like LaCie or other things ?

**Comment by 4shadowr** [comment]
No, I Don't think so I just Clicked Allow and Restart

**Comment by chris1111** [comment]
you don't have a native wifi on your MacBook

**Comment by 4shadowr** [comment]
I Uninstalled using the installer File -> Restarted
Re-installed it
This time it didn't ask me to allow
<img width="662" alt="Screenshot 2020-07-15 at 5 22 18 PM" src="https://user-images.githubusercontent.com/9377704/87541938-bf5fc800-c6bf-11ea-83db-0cabfd6b3751.png">
Restarted again too still not working
How to do a clean Re-install ?

**Comment by 4shadowr** [comment]
> you don't have a native wifi on your MacBook

I think Built-in WiFi Adapter is broken or something
No Stores are open due to pandemic :(

**Comment by chris1111** [comment]
Strange because we don't have a installer

**Comment by 4shadowr** [comment]
> Strange because we don't have a Uninstaller file

NOT an Uninstaller file, the installer package
<img width="611" alt="Screenshot 2020-07-15 at 5 26 52 PM" src="https://user-images.githubusercontent.com/9377704/87542304-617fb000-c6c0-11ea-9eba-e7071d881fa8.png">

**Comment by 4shadowr** [comment]
Can you tell me with how to do a clean Uninstall
So I can do a Fresh Install again ?

**Comment by chris1111** [comment]
Send me system report of your MacBook Pro on **About this Mac** ➤ /File /save 
then put here on ZIP file of the system report

**Comment by 4shadowr** [comment]
[MacBook Pro.zip](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/files/4925443/MacBook.Pro.zip)

**Comment by chris1111** [comment]
boot to the recovery then try to setup SIP disable just for trying again
in the recovery open Utility /Terminal type
csrutil disable
Closed then reboot and retry the program
let me know

**Comment by 4shadowr** [comment]
Worked like a charm
Thanks !!

> boot to the recovery then try to setup SIP disable just for trying again
> in the recovery open Utility /Terminal type
> csrutil disable
> Closed then reboot and retry the program
> let me know
