### ISSUE TITLE
Not working DWA-131 E1 MBP Mid 2012

### ISSUE THREAD

**Issue by MEANcisco** [chris1111/Wireless-USB-Big-Sur-Adapter#7]
Hello!

I'm using the MBP mid 2012 beta (unsupported) with big sur and it is not working, it is just for information.
If i can do extra steps to make it work, please notice me.
else i can help you to test if you do not have this unsupported model.

Thanks for your work, this is simply amazing.

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/6
