### ISSUE TITLE
Is it possible to add RT2870?

### ISSUE THREAD

**Issue by Mijail** [chris1111/Wireless-USB-Big-Sur-Adapter#70]
Hi!

I've been searching all the internet to find a way to make my AWUS036NH work with my original mac os Big Sur, but all my searches end here which if I am not mistaken it is not the right place. Is it possible to add to this package the drivers I need?

Thanks!

**Comment by chris1111** [comment]
No not its a Mediatek drivers not support anymore after Mojave
