### ISSUE TITLE
BT Wi-Fi Authentication Page is not showing

### ISSUE THREAD

**Issue by jakemike1** [chris1111/Wireless-USB-Big-Sur-Adapter#71]
Hi,

First of all I would like to say thank you for doing great job on making Wi-Fi adapters to work on Big Sur.

I am having issue when connecting to BT Wi-Fi hotspot. When connected I should see the authentication webpage. The problem is that the page is not showing when connected using the TP-Link Archer T9UH v2. I tried connecting to authentication page (captive.apple.com and www.btwifi.co.uk:8443) manually but the pages are not loading when using the TP-Link adapter.

Any ideas please?

**Comment by chris1111** [comment]
The page not loading using network cable 😂
![Capture d’écran, le 2021-02-26 à 10 01 42](https://user-images.githubusercontent.com/6248794/109316458-a4d6fb00-7819-11eb-99b8-d662dd371384.png)

**Comment by jakemike1** [comment]
Are you connected to the BT Wi-fi Hotspot?

**Comment by chris1111** [comment]
no but BT USB Realtek adapter not working in macOS , BT never working

**Comment by jakemike1** [comment]
BT is a company name 😉 not Bluetooth. Sorry, I should have mentioned that in the first place.

It’s like connecting to public unsecured wifi hotspot, when you connect the window pops up with authentication page where you type in you credentials. Just like at the airport, hotel or any other public WiFi’s.

The problem is that the authentication page does not appear when using the Archer with your drivers and I am unable to connect to the page manually.

**Comment by chris1111** [comment]
I don't think that's working you need to address this issue at Realtek or TP Link because even with the TP Link drivers this is not working I am pretty sure somme people already post issue about that
