### ISSUE TITLE
wifi dongle adapter (rt5370) not working in BS11.1. Worked in catalina  

### ISSUE THREAD

**Issue by neuberfran** [chris1111/Wireless-USB-Big-Sur-Adapter#72]
Hi,

https://docs.google.com/document/d/1zRFudK9icFa2KaejitafkHqLBSYzcqrCCckCBC2U6SY/edit

I have ralink rt5370 (from lsusb in ubuntu) here. In hackintosh catalina it worked.

In BS11.1 it not work. Why? 

1) i disable the SecureBootModel 
2) I disable the Sip

![foto](https://user-images.githubusercontent.com/38701397/109353193-c86e6580-785a-11eb-97ed-8f3fce0caa70.png)

**Comment by chris1111** [comment]
ralink rt5370 Its a Mediatek drivers, this is not working after High Sierra 10.13
Not support here 🤭

**Comment by neuberfran** [comment]
@chris1111 As I said above, rt5370 was running normally at 10.15.7.

**Comment by chris1111** [comment]
> @chris1111 As I said above, rt5370 was running normally at 10.15.7.


https://www.mediatek.com/products/broadbandwifi/rt5370

**Comment by neuberfran** [comment]
@chris1111  pls. My last question is: From the list of compatible wifi usb adapters on your github (with BS11.1, of course) which is the cheapest?
