### ISSUE TITLE
RT2870 version

### ISSUE THREAD

**Issue by pjfa** [chris1111/Wireless-USB-Big-Sur-Adapter#77]
Hi there, is there any compatible version with RT2870?

**Comment by chris1111** [comment]
See here
https://github.com/chris1111/USB-Wireless-Utility

**Comment by zeay23** [comment]
> Hi there, is there any compatible version with RT2870?

Were you able to resolve your problem? i have the same rt2870 and have no luck

**Comment by pjfa** [comment]
unfortunately no
