### ISSUE TITLE
Ralink 3070 - Mac Big Sur Issue or chip not supported

### ISSUE THREAD

**Issue by nikolai-mitnik** [chris1111/Wireless-USB-Big-Sur-Adapter#96]
Hi Chris, first of all thank you very much for your hard work on this.

The card is an Alpha Network - Model: AWUS036NH

Maybe is not an issue, just a chip (Ralink 3070) not supported, but tried to use your tool with no luck, do you know if you can add support to this chip, in case it's not supported ? 

Thanks in advance!

Best!

**Comment by chris1111** [comment]
Hi Nikolai this chip is not support anymore by the developer since macOS Mojave, I made a program to make it work but In Mojave and Catalina that's it
https://github.com/chris1111/USB-Wireless-Utility

**Comment by nikolai-mitnik** [comment]
Thank for your quick response! 

I imagined something like that, thank you for your time!
