### ISSUE TITLE
Not working on Big Sur 11.4

### ISSUE THREAD

**Issue by edzordzinam** [chris1111/Wireless-USB-Big-Sur-Adapter#97]
After upgrading to Big Sur 11.4 TP-WN823N no longer works. 

Was working on 11.3.1 until the recent update to 11.4

Was using release V-7.

Both Gatekeeper and SIP are disabled but device driver is still not loading.

  Model Name:	MacBook Pro (Early 2015)
  Model Identifier:	MacBookPro12,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  
  System Version:	macOS 11.4 (20F71)
  Kernel Version:	Darwin 20.5.0
  Boot Volume:	MacOS
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Disabled

**Comment by chris1111** [comment]
Surely not fully disable because its work here , also work on latest Beta

**Comment by anjianyu** [comment]
I have the same problem

**Comment by AlexVanchov** [comment]
Same
